displayName: Artika - Produkt Managerin
schemaName: crb27_ArtikaProduktManagerin
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

    - id: Telephony
      channelId: Telephony

    - channelId: MsTeamsPhone

  settings:
    GenerativeActionsEnabled: true
    TelephonyInitialized: true

  isTelephonyEnabled: true
  isAgentConnectable: true
  voiceProcessingMode:
    kind: ClassicVoiceProcessingMode

  botSpeechSettings:
    silenceDetectionTimeoutInMilliseconds: 0
    isDomainLanguageModelEnabled: false

  publishOnImport: true
  gPTSettings:
    defaultSchemaName: crb27_ArtikaProduktManagerin.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

  deferredProvisioning: false

publishedOn: 2026-08-20T17:26:18.0000000Z
template: default-2.1.0
language: 1031