displayName: Dori - Dokument Analystin
schemaName: crb27_DoriDokumentAnalystin
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: crb27_DoriDokumentAnalystin.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-08-13T12:41:39.0000000Z
template: default-2.1.0
language: 1031