displayName: Erkan
schemaName: crb27_Erkan
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnCreate: false
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: crb27_Erkan.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

  deferredProvisioning: false

publishedOn: 2026-08-12T14:58:59.0000000Z
template: default-2.1.0
language: 1031